export function Footer() {
  return (
    <footer className="border-t border-slate-200 bg-slate-50">
      <div className="mx-auto max-w-6xl px-6 py-4 text-xs text-brand-gray">
        Documents generated by Prelegal are AI-assisted drafts only. They do not constitute legal advice and
        should be reviewed by a qualified attorney before use.
      </div>
    </footer>
  );
}
